# Generated by Django 4.1.7 on 2023-05-01 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("magasin", "0032_lignepanier_panier_lignepanier_panier_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="lignepanier", name="panier",),
        migrations.RemoveField(model_name="lignepanier", name="prix_unitaire",),
        migrations.RemoveField(model_name="panier", name="date_creation",),
        migrations.RemoveField(model_name="panier", name="produits",),
        migrations.RemoveField(model_name="panier", name="total",),
        migrations.RemoveField(model_name="panier", name="utilisateur",),
        migrations.AddField(
            model_name="lignepanier",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="panier",
            name="lignes_panier",
            field=models.ManyToManyField(to="magasin.lignepanier"),
        ),
        migrations.AddField(
            model_name="panier",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lignepanier",
            name="produit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="magasin.produit",
            ),
        ),
        migrations.AlterField(
            model_name="lignepanier",
            name="quantite",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
