# Generated by Django 4.1.7 on 2023-05-02 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("magasin", "0034_remove_panier_lignes_panier_remove_panier_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="panier", name="produits",),
        migrations.RemoveField(model_name="panier", name="total",),
        migrations.AddField(
            model_name="panier",
            name="produit",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="magasin.produit",
            ),
        ),
        migrations.AddField(
            model_name="panier", name="quantite", field=models.IntegerField(default=1),
        ),
    ]
