# Generated by Django 4.1.7 on 2023-05-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magasin", "0038_contenupanier"),
    ]

    operations = [
        migrations.AddField(
            model_name="panier",
            name="status",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("en_cours", "En cours de traitement"),
                    ("livree", "Livrée"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
